apiVersion: v1
kind: ConfigMap
metadata:
  name: workspace-engine-config
  namespace: workspace-engine
  labels:
    app.kubernetes.io/name: workspace-engine
    app.kubernetes.io/part-of: workspace-engine
data:
  PROJECT_NAME: "WorkspaceEngine"
  VERSION: "1.0.0"
  API_V1_PREFIX: "/api/v1"
  DEBUG: "false"
  S3_ENDPOINT: "http://minio-service:9000"
  S3_BUCKET: "workspace-engine-uploads"
  S3_REGION: "us-east-1"
  CORS_ORIGINS: '["http://localhost:3000","http://127.0.0.1:3000","http://workspace.local"]'
  NEXT_PUBLIC_API_URL: "/api/v1"
  NEXT_PUBLIC_WS_PORT: "80"
